/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pbo.arsipsurat;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reno
 */
public class SuratKeluar extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuForm
     */
    public SuratKeluar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelsuratkeluar = new javax.swing.JTable();
        inputNomorSurat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        inputTanggalSurat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputPerihal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputLampiran = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputPenerima = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonTambah = new javax.swing.JButton();
        tombolhapus = new javax.swing.JButton();
        backtomain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelsuratkeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor Surat", "Tanggal Surat", "Penerima", "Perihal", "Lampiran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelsuratkeluar.setColumnSelectionAllowed(false);
        tabelsuratkeluar.getTableHeader().setReorderingAllowed(false);
        databaseConnection connect = new databaseConnection();
        Connection connectDB = connect.getConnection();
        String query = "SELECT * FROM suratkeluar";
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Nomor Surat","Tanggal Surat","Penerima","Perihal","Lampiran"},0);
        try{
            Statement statement = connectDB.createStatement();
            ResultSet queryResult = statement.executeQuery(query);
            while (queryResult.next()){
                String column1 = queryResult.getString("nomorsurat");
                String column2 = queryResult.getString("tanggalsurat");
                String column3 = queryResult.getString("penerima");
                String column4 = queryResult.getString("perihal");
                String column5 = queryResult.getString("lampiran");
                model.addRow(new Object[]{column1,column2,column3,column4,column5});

            }
            tabelsuratkeluar.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        jScrollPane1.setViewportView(tabelsuratkeluar);
        tabelsuratkeluar.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        inputNomorSurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomorSuratActionPerformed(evt);
            }
        });

        jLabel1.setText("Nomor Surat");

        inputTanggalSurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTanggalSuratActionPerformed(evt);
            }
        });

        jLabel2.setText("Tanggal Surat");

        inputPerihal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPerihalActionPerformed(evt);
            }
        });

        jLabel3.setText("Perihal");

        inputLampiran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLampiranActionPerformed(evt);
            }
        });

        jLabel4.setText("Lampiran");

        inputPenerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPenerimaActionPerformed(evt);
            }
        });

        jLabel5.setText("Penerima");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Surat Keluar");

        buttonTambah.setText("Tambah/Update");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        tombolhapus.setText("Hapus");
        tombolhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolhapusActionPerformed(evt);
            }
        });

        backtomain.setText("Back to Main Menu");
        backtomain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtomainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(buttonTambah))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(inputPerihal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(inputPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(inputTanggalSurat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(inputNomorSurat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputLampiran, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolhapus)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backtomain)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backtomain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNomorSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputTanggalSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputPerihal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputLampiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(buttonTambah)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolhapus)
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNomorSuratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomorSuratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomorSuratActionPerformed

    private void inputTanggalSuratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTanggalSuratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTanggalSuratActionPerformed

    private void inputPerihalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPerihalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPerihalActionPerformed

    private void inputLampiranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLampiranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLampiranActionPerformed

    private void inputPenerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPenerimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPenerimaActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:

        String no_surat = inputNomorSurat.getText();
        String tanggalsurat = inputTanggalSurat.getText();
        String perihal = inputPerihal.getText();
        String lampiran = inputLampiran.getText();
        String penerima = inputPenerima.getText();

        databaseConnection connect = new databaseConnection();
        Connection connectDB = connect.getConnection();
        String qupdate = "INSERT INTO suratkeluar(nomorsurat,tanggalsurat,penerima,perihal,lampiran) VALUES('" + no_surat + "','" + tanggalsurat + "','" + penerima + "','" + perihal + "','" + lampiran + "')";
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Nomor Surat", "Tanggal Surat", "Penerima", "Perihal", "Lampiran"}, 0);
        try {
            Statement statement = connectDB.createStatement();
            statement.executeUpdate(qupdate);

            loadTable();

        } catch (SQLException e) {
            String updatedata = "UPDATE suratkeluar SET nomorsurat = '" + no_surat + "',tanggalsurat = '" + tanggalsurat + "',penerima ='" + penerima + "',perihal='" + perihal + "',lampiran='" + lampiran + "'WHERE nomorsurat='" + no_surat + "'";
//            String queryy = "SELECT * FROM suratmasuk";
//            DefaultTableModel modelll = new DefaultTableModel(new Object[]{"Nomor Surat", "Tanggal Surat", "Penerima", "Perihal", "Lampiran"}, 0);
            try {
                Statement statement = connectDB.createStatement();
                statement.executeUpdate(updatedata);
                loadTable();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    

            }//GEN-LAST:event_buttonTambahActionPerformed

    private void backtomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtomainActionPerformed
        MainMenu MainMenu = new MainMenu();
        MainMenu.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backtomainActionPerformed


    private void tombolhapusActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        databaseConnection connect = new databaseConnection();
        Connection connectDB = connect.getConnection();


        if (tabelsuratkeluar.getSelectedRowCount() == 1) {
            int selectvalue = tabelsuratkeluar.getSelectedRow();
            Object selecteddata = tabelsuratkeluar.getValueAt(selectvalue, 0);
            String convertedSelectedData = String.valueOf(selecteddata);
            loadTable();
            String query = "DELETE FROM suratkeluar WHERE nomorsurat = '" + convertedSelectedData + "'";
//            DefaultTableModel modelll = new DefaultTableModel(new Object[]{"Nomor Surat", "Tanggal Surat", "", "Perihal", "Lampiran"}, 0);
            try {
                Statement statement = connectDB.createStatement();
                statement.executeUpdate(query);
                loadTable();


            }                                            
            catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }


    private void loadTable(){
        databaseConnection connect = new databaseConnection();
        Connection connectDB = connect.getConnection();
        String query = "SELECT * FROM suratkeluar";
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Nomor Surat","Tanggal Surat","Penerima","Perihal","Lampiran"},0);
        try{
            Statement statement = connectDB.createStatement();
            ResultSet queryResult = statement.executeQuery(query);
            while (queryResult.next()){
                String column1 = queryResult.getString("nomorsurat");
                String column2 = queryResult.getString("tanggalsurat");
                String column3 = queryResult.getString("penerima");
                String column4 = queryResult.getString("perihal");
                String column5 = queryResult.getString("lampiran");
                model.addRow(new Object[]{column1,column2,column3,column4,column5});


            }
            tabelsuratkeluar.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        }


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuratKeluar().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtomain;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JTextField inputLampiran;
    private javax.swing.JTextField inputNomorSurat;
    private javax.swing.JTextField inputPenerima;
    private javax.swing.JTextField inputPerihal;
    private javax.swing.JTextField inputTanggalSurat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelsuratkeluar;
    private javax.swing.JButton tombolhapus;
    // End of variables declaration//GEN-END:variables
}
